### ISSUE TITLE
Attribute changes cause values from incoming context to be missed on merge

### ISSUE THREAD

**Issue by dark-panda** [aaronmallen/activeinteractor#151]
#### Current Behavior
Attributes are missed when merging an incoming context into another context. This was discovered when using an organizer.

#### Expected Behavior
Either all values should be copied into the context or only explicitly named attributes, depending on design goals.

#### Steps to Reproduce
I've discovered a bug in this PR that isn't covered by a spec: when you are using an organizer, the context values in the organizer's steps don't get initialized properly. Basic case:

```ruby
class TestInteractor < ApplicationInteractor
  def perform
    p context
    p context['user']
    p context.user
  end
end

class TestInteractorContext < ApplicationContext
  attributes :user
end

class TestOrganizer < ApplicationInteractorOrganizer
  organize :test_interactor
end

TestOrganizer.perform(user: 'foo')
```

Output before change:

```
#<TestInteractorContext user="foo">
"foo"
"foo"
TestOrganizer::Context {
    :user => "foo"
}
```

Output after change:

```
#<TestInteractorContext user="foo">
"foo"
nil
TestOrganizer::Context {
    :user => "foo"
}
```

#### Additional Comments

A branch with modified attributes code that only copies over named attributes is available at https://github.com/dark-panda/activeinteractor/tree/attribute-merging-fixes, but it is known to be incomplete pending some design decisions.

**Comment by aaronmallen** [comment]
caused by #138

**Comment by aaronmallen** [comment]
The original behavior was the context was intended to be a catch all.  You should be able to assign any variable to the context and then return attributes explicitly defined on the context with the `#attributes` instance method:

```ruby
class MyContext < ActiveInteractor::Context::Base
  attributes :foo
end

context = MyContext.new(foo: 'foo', bar: 'bar')
context.attributes 
#=> { foo: 'foo' }
context.bar
#=> 'bar'
```

Acceptance criteria for this bug is to restore the intended functionality while also supporting an api friendly to libraries that expect the `ActiveModel::Attributes` api.

**Comment by aaronmallen** [comment]
@dark-panda maybe I'm miss understanding the underlying issue.  I'm actually unable to reproduce the bug.  See this spec: https://github.com/aaronmallen/activeinteractor/blob/bugfix/%23151/spec/integration/a_basic_organizer_spec.rb#L98

**Comment by dark-panda** [comment]
Here's another spec then that shows the issue. The following spec succeeds in v1.0.0 but fails in the current master at 64e12ec254e6bb2b0a01ca442c9ca47737665323.

```ruby
context 'with attributes in the contexts' do
  before do
    build_interactor('TestInteractor') do
      def perform
        context.has_foo_as_method = context.foo.present?
        context.has_foo_as_element = context['foo'].present?
        context.has_bar_as_method = context.bar.present?
        context.has_bar_as_element = context['bar'].present?
      end
    end

    build_context('TestInteractorContext') do
      attributes :foo
    end

    build_organizer('TestOrganizer') do
      organize :test_interactor
    end
  end

  it 'copies over all attributes in the contexts to each interactor' do
    result = TestOrganizer.perform(foo: 'hello', bar: 'world')

    expect(result.has_foo_as_method).to be true
    expect(result.has_foo_as_element).to be true
    expect(result.has_bar_as_method).to be true
    expect(result.has_bar_as_element).to be true
  end
end
```

So, this spec works in v1.0.0 but fails in master, and it's due to `#merge_attribute_values`, because that method will only copy over named attributes when `context` responds to `#attributes`, which in this case is what the organizer is passing along to the interactor. In v1.0.0, all attributes were copied over because they were just properties of an OpenStruct effectively, but in master they must be explicitly named in a context under certain situations, and using an organizer is one such situation.

**Comment by aaronmallen** [comment]
@dark-panda can you try it out with the following in your gemfile:

```ruby
gem 'activeinteractor', require: 'active_interactor', github: 'aaronmallen/activeinteractor', branch: 'bugfix/#151'
```

**Comment by dark-panda** [comment]
The spec mentioned above still fails when applied to the bugfix/#151 branch.

**Comment by aaronmallen** [comment]
@dark-panda did you try it after I updated the branch? `bundle update`

**Comment by aaronmallen** [comment]
https://github.com/aaronmallen/activeinteractor/pull/152 is passing with your spec?
