### ISSUE TITLE
[Bug Report] Context validation is rolling back an interactor that was never performed

### ISSUE THREAD

**Issue by mohameddiaa27** [aaronmallen/activeinteractor#214]
```ruby
class FooInteractor < ActiveInteractor::Base
  def perform
    puts "Performed"
  end

  def rollback
    puts 'Rolling Back'
  end
end

class FooInteractor::Context < ::ActiveInteractor::Context::Base
  attribute :foo
  validates :foo, presence: true
end
```

#### Current Behavior
Rolls back the current interactor
```ruby
FooInteractor.perform
# Rolling Back
```

#### Expected Behavior

Context Validations should add errors and fail context without rolling back the current interactor that was never performed.
```ruby
FooInteractor.perform
```

#### Steps to Reproduce

1.

**Comment by aaronmallen** [comment]
The interactor is performed in this case as validations are part of the perform step.  I would recommend using safe navigation in your rollback methods:

```ruby
def rollback
  context.user&.delete
end
```
