### ISSUE TITLE
No validation errors when validation fails on: :calling or on: :called

### ISSUE THREAD

**Issue by nlinn** [aaronmallen/activeinteractor#222]
#### Current Behavior

activeinteractor (1.0.4)
When I specify a validation to be performed **on: :calling** or **on: :called** and this validation fails:

- `result.success?` is false (expected)
- `result.valid?` is true (unexpected)
- `result.errors.any?` is false (unexpected)

#### Expected Behavior

If I omit the **on: ...** the result is

- `result.success?` is false
- `result.valid?` is false
- `result.errors.any?` is true

I expect the same result when using **on: :calling** or **on: :called**

#### Steps to Reproduce

I'm using:
activeinteractor (1.0.4)
rails (5.2.4.1)
activesupport etc. (5.2.4.1)

Simple example:
https://gist.github.com/nlinn/fbd0ee2fcabe67ecacefa68de731bb2d

**Comment by aaronmallen** [comment]
This behavior is intended, the `on: :calling` and `on: :called` hooks are meant to allow developers to require an attribute to be present before an interactor's `#perform` method is invoked to quick fail if the attribute isn't there or to allow for some automated failures if attributes are not present after an interactor's `#perform` method is invoked.  There are many cases when you may need an attribute present before invoking the interactor but don't need it present when the context is output.

**Comment by aaronmallen** [comment]
Scratch that I see from your gist the issue is it's not quick failing and returning the appropriate validation errors.

**Comment by pandwoter** [comment]
@nlinn 
Hello, I investigated following issue a little

so it seems that when you call ```result.valid?``` (when you are using ```on: :calling || :called```)

```ruby
def valid?(context = nil)
  current_context, self.validation_context = validation_context, context
  errors.clear
  run_validations!
ensure
  self.validation_context = current_context
end
```

this ```ActiveModel::Validations#valid?``` piece resets errors to initial empty state(couse we not providing it a validation context)

one possible workaround is to use:
```rube
result.success? #=> false
result.valid?(:calling) #=> false
result.errors.any? #=> true
```

if this behavior is unwanted I can try to re-implement this
@aaronmallen what do you think?

**Comment by aaronmallen** [comment]
@pandwoter yes that is the issue however the intention behind the `ActiveModel` implementation was to verify that an object was valid even after change and ideally we would want our object to behave in the same way. One concern I have is that this will entail overwriting `valid?` on our object which I would rather not do.

**Comment by aaronmallen** [comment]
We'll ensure we address this in version 2.0 of the gem but for now the best solution is to not call `valid?` on a context object that inherits from `ActiveInteractor::Context::Base` and just inspect its errors.
