### ISSUE TITLE
Update the wiki with inplace callbacks

### ISSUE THREAD

**Issue by mohameddiaa27** [aaronmallen/activeinteractor#252]
#### Elevator pitch, describe and sell us your feature request

**As a** developer,
**I want** be able to have documentation about in place Callbacks
**so that** I could use the functionality

#### Is your feature request related to a problem

see https://github.com/aaronmallen/activeinteractor/issues/247
see https://github.com/aaronmallen/activeinteractor/pull/246

#### Additional Comments

I'm not able to update the wiki since it is open only for collabrators, Here is an example of what we can add to the `inplace callbacks` section:

We can do worker `before` or `after` [perform](https://www.rubydoc.info/gems/activeinteractor/ActiveInteractor/Base#perform-instance_method) which will be invoked on a specific [interactor](https://www.rubydoc.info/gems/activeinteractor/ActiveInteractor/Base) in an [organizer](https://github.com/aaronmallen/activeinteractor/wiki/Interactors#organizers) by passing a block or passing a method name to the [.organize](https://www.rubydoc.info/gems/activeinteractor/ActiveInteractor/Organizer/Base#organize-class_method) method:

```ruby
class MyInteractor1 < ActiveInteractor::Base
  def perform
    puts 'MyInteractor1'
  end
end

class MyInteractor2 < ActiveInteractor::Base
  def perform
    puts 'MyInteractor2'
  end
end

class MyOrganizer < ActiveInteractor::Organizer::Base
  organized do
    add MyInteractor1
    add MyInteractor2, before: -> { puts "Before" }, after: :print_after
  end

  private

  def print_after
    puts "After"
  end
end

MyOrganizer.perform
"MyInteractor1"
"Before"
"MyInteractor2"
"After"
#=> <MyOrganizer::Context...>
```

**Comment by aaronmallen** [comment]
https://github.com/aaronmallen/activeinteractor/wiki/Interactors#organized-interactor-callbacks

**Comment by mohameddiaa27** [comment]
Thank you 🙏
